main1/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
    # подключались к главному приложению с префиксом products/.
    path('products/', include('simpleapp.urls')),
    path('news/', include('simpleapp.urls')),
    path('articles/', include('simpleapp.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include(('appointments.urls', 'appointments'), namespace='appointments'))
]

main1/simpleapp/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse


# Товар для нашей витрины
class Product(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True, # названия товаров не должны повторяться
    )
    description = models.TextField()
    quantity = models.IntegerField(
        validators=[MinValueValidator(0)],
    )
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products', # все продукты в категории будут доступны через поле products
    )
    price = models.FloatField(
        validators=[MinValueValidator(0.0)],
    )

    def __str__(self):
        return f'{self.name}: {self.description[:20]}'


# Категория, к которой будет привязываться товар
class Category(models.Model):
    # названия категорий тоже не должны повторяться
    name = models.CharField(max_length=100, unique=True)
    subscribers = models.ManyToManyField(User, related_name='subscribers_categories', blank=True)
    def __str__(self):
        return self.name



class News(models.Model):
    objects = None
    name = models.CharField(max_length=50, unique=True)
    text = models.TextField()
    date_published = models.DateTimeField(default=datetime.now)
    author = models.ForeignKey('Author', on_delete=models.CASCADE)

    def __init__(self, *args, **kwargs):
        super().__init__(args, kwargs)
        self.id = None

    def __str__(self):
        return f'{self.name} {self.text}'

    def send_update_email(self):
        subject = f'Обновление в категории: {self.category.name}'
        message = f'{self.name}\n\n{self.text[:50]}'
        subscribers_emails = self.category.subscribers.values_list('email', flat=True)
        send_mail(subject, message, 'noreply@example.com', list(subscribers_emails), fail_silently=True)

    @property
    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __init__(self, *args, **kwargs):
        super().__init__(args, kwargs)
        self.comment_set = None
        self.post_set = None


    def update_rating(self):
        post_rating = self.post_set.aggregate(models.Sum('rating'))['rating__sum'] or 0
        comment_rating = self.comment_set.aggregate(models.Sum('rating'))['rating__sum'] or 0
        comment_post_rating = self.post_set.aggregate(models.Sum('comment__rating'))['comment__rating__sum'] or 0

        self.rating = (post_rating * 3) + comment_rating + comment_post_rating
        self.save()


class Post(models.Model):
    type_choices = [('news', 'News'), ('post', 'Post')]

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=20, choices=type_choices)
    created = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=200)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        preview_length = 124
        if len(self.text) <= preview_length:
            return self.text
        else:
            return self.text[:preview_length] + '...'


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

main1/templates/appointment_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>{{ appointment.client_name }} Спасибо за запись!</h2>
    <p> Вы записаны на {{ appointment.date|date:"d-M-Y" }} по вопросу: {{ appointment.message|truncatechars:50 }} </p>
</body>
</html>

main1/templates/article_delete.html
{% extends 'default.html' %}

{% block content %}
    <h2>Вы уверены, что хотите удалить эту статью?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
        <a href="{% url 'article_list' %}">Отмена</a>
    </form>
{% endblock %}

main1/templates/article_edit.html
{% extends 'default.html' %}

{% block content %}
    <h2>Статья</h2>
<hr>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

main1/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

main1/templates/news.html
{% extends 'flatpages/default.html'%}

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>Все новости</h1>
    <hr>
    {% if news %}
        <table>
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Текст</td>

            </tr>
            {% for one_news in news %}
            <tr>
                <td>{{ news.name }}</td>
                <td>{{ news.date_published|date:'M d Y' }}</td>
                <td>{{ news.text|trancatechars:20}}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нету</h2>
    {% endif %}
    {% if page_obj.has_previos %}
        <a href="?page=1">1</a>
        {% if page_obj.previos_page_number != 1%}
            <a href="?page={{page_obj.previos_has_number}}">{{page_obj.previos_has_number}}</a>
        {% endif%}
    {% endif%}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number}}">{{ page_obj.next_page_number}}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            <a href="?page={{ page_obj.paginator_num_pages }}"> {{ page_obj.paginator_num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

main1/templates/news_edit.html
{% extends 'default.html' %}

{% block content %}
    <h2>Новость</h2>
<hr>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

main1/templates/news_search.html
{% extends 'default.html' %}

{% block content %}
    <h1>Search News</h1>

    <form action="{% url 'news_search' %}" method="get">
        <input type="submit" value="Найти">
    </form>

    {% if news_results %}
        <h2>Поиск новостей:</h2>
        <ul>
            {% for news in news_results %}
                <li>{{ news.name }} - {{ news.author }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет результатов поиска.</p>
    {% endif %}
{% endblock %}

main1/templates/news_sub_cat.html
<h1>Здравствуй, {{ username }}. Новая статья в твоём любимом разделе!</h1>
<hr>
{% for category in categories %}
    <h2>{{ category.name }}</h2>
    {% for news in category.news_set.all %}
        <div>
            <h3>{{ news.title }}</h3>
            <p>{{ news.content|safe|truncatechars:50 }}</p>
        </div>
    {% endfor %}
    <a href="{% url 'subscribe_category' category.id %}">
        {% if user in category.subscribers.all %}
            Отписаться
        {% else %}
            Подписаться
        {% endif %}
    </a>
{% endfor %}

main1/templates/one_news.html
{% extends 'flatpages/default.html'%}

{% block title %}
News
{% endblock title %}


{% block content %}
<h1> {{ one_news }}</h1>
{% endblock content %}

main1/templates/product.html
{% extends 'flatpages/default.html' %}

{% block title %}
Product
{% endblock title %}

{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

main1/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

main1/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

main1/templates/products.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{# Импортируем модуль с нашим тегом #}
{% load custom_tags %}

{% block title %}
Products
{% endblock title %}

{% block content %}
   <h1>Все товары</h1>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if products %}
       <table>
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Категория</td>
               <td>Цена</td>
               <td>Количество</td>
           </tr>

           {% for product in products %}
           <tr>
               <td>{{ product.name }}</td>
               <td>{{ product.description|truncatechars:15 }}</td>
               <td>{{ product.category.name }}</td>
               <td>{{ product.price|currency }}</td>
               <td>{{ product.quantity }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Товаров нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

main1/templates/protected_page.html
{% extends 'default.html' %}

{% block title %}
    Защищенная страница
{% endblock %}

{% block content %}
    <h1>Добро пожаловать на защищенную страницу!</h1>
    <p>Это страница, которая доступна только аутентифицированным пользователям.</p>
    <p>Здесь может быть ваш контент и функциональность, которую хотите отобразить только для авторизованных пользователей.</p>
{% endblock %}